/*
# Create settings, notifications, api_keys, and integrations tables

1. New Tables
- `settings` — single-row table storing organization profile, branding, and workspace config
  - id (int, primary key, always 1), org_name, website, industry, timezone, logo_path,
    primary_color, theme, updated_at
- `notifications` — real notifications generated by CRM events
  - id (uuid), title, description, type, record_type, record_id, read (bool), created_at
- `api_keys` — API keys for workspace access
  - id (uuid), name, key_hash (text, the SHA-256 hash), key_prefix (text, first 8 chars for display),
    created_at, revoked_at
- `integrations` — integration connection state
  - id (uuid), service (text, unique), connected (bool), config (jsonb), created_at, updated_at
- `role_permissions` — per-role CRUD permissions per module
  - id (uuid), role (text), module (text), can_view (bool), can_create (bool), can_edit (bool), can_delete (bool)

2. Security
- Enable RLS on all new tables.
- Allow anon + authenticated full CRUD (single-tenant, no auth).

3. Notes
- `settings` uses a fixed id of 1 so we always have exactly one row (upsert pattern).
- API keys store only the hash and a display prefix — never the raw key.
*/

CREATE TABLE IF NOT EXISTS settings (
  id int PRIMARY KEY DEFAULT 1,
  org_name text NOT NULL DEFAULT 'MEHANS Real Estate',
  website text,
  industry text DEFAULT 'Real Estate',
  timezone text DEFAULT 'America/New_York',
  logo_path text,
  primary_color text DEFAULT '#D4AF37',
  theme text DEFAULT 'dark',
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public all settings" ON settings;
CREATE POLICY "public all settings" ON settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Seed the single row if it doesn't exist
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  type text DEFAULT 'info',
  record_type text,
  record_id uuid,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public all notifications" ON notifications;
CREATE POLICY "public all notifications" ON notifications FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  key_hash text NOT NULL,
  key_prefix text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public all api_keys" ON api_keys;
CREATE POLICY "public all api_keys" ON api_keys FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  service text UNIQUE NOT NULL,
  connected boolean NOT NULL DEFAULT false,
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE integrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public all integrations" ON integrations;
CREATE POLICY "public all integrations" ON integrations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Seed default integrations
INSERT INTO integrations (service, connected) VALUES
  ('Slack', false),
  ('Gmail', false),
  ('WhatsApp Business', false),
  ('Google Calendar', false),
  ('OpenAI', false),
  ('Zapier', false)
ON CONFLICT (service) DO NOTHING;

CREATE TABLE IF NOT EXISTS role_permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  role text NOT NULL,
  module text NOT NULL,
  can_view boolean NOT NULL DEFAULT true,
  can_create boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  UNIQUE(role, module)
);

ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public all role_permissions" ON role_permissions;
CREATE POLICY "public all role_permissions" ON role_permissions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Seed default permissions: Admin gets full access, others get limited
INSERT INTO role_permissions (role, module, can_view, can_create, can_edit, can_delete) VALUES
  ('admin', 'leads', true, true, true, true),
  ('admin', 'properties', true, true, true, true),
  ('admin', 'deals', true, true, true, true),
  ('admin', 'tasks', true, true, true, true),
  ('admin', 'meetings', true, true, true, true),
  ('admin', 'contacts', true, true, true, true),
  ('manager', 'leads', true, true, true, false),
  ('manager', 'properties', true, true, true, false),
  ('manager', 'deals', true, true, true, false),
  ('manager', 'tasks', true, true, true, true),
  ('manager', 'meetings', true, true, true, false),
  ('manager', 'contacts', true, true, true, false),
  ('agent', 'leads', true, true, true, false),
  ('agent', 'properties', true, false, false, false),
  ('agent', 'deals', true, true, false, false),
  ('agent', 'tasks', true, true, true, false),
  ('agent', 'meetings', true, true, true, false),
  ('agent', 'contacts', true, true, true, false),
  ('viewer', 'leads', true, false, false, false),
  ('viewer', 'properties', true, false, false, false),
  ('viewer', 'deals', true, false, false, false),
  ('viewer', 'tasks', true, false, false, false),
  ('viewer', 'meetings', true, false, false, false),
  ('viewer', 'contacts', true, false, false, false)
ON CONFLICT (role, module) DO NOTHING;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(read);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_keys_revoked ON api_keys(revoked_at);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role);
